### ISSUE TITLE
Missing quote in azurecopy.exe.config

### ISSUE THREAD

**Issue by lukaskabrt** [kpfaulkner/azurecopy#1]
The latest release [https://github.com/kpfaulkner/azurecopy/releases/download/0.16.1/azurecopy-0.16.1.7z] contains invalid azurecopy.exe.config file.

There is a missing quote in the following line
    `<add key="SkyDriveRefreshToken" value=" />`

**Comment by kpfaulkner** [comment]
Hi Lukas,

Thanks, I'll fix that later today.

Ken

**Comment by kpfaulkner** [comment]
Created 0.16.2 which fixes the broken config.
