### ISSUE TITLE
Aborting a copy operation

### ISSUE THREAD

**Issue by vivekanandia** [kpfaulkner/azurecopy#12]
I started a copy operation for 3 TB data from s3 to blob and am having problem aborting it.

Unknown error generated. Please report to Github page https://github.com/kpfaulk
ner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag. Micro
soft.WindowsAzure.Storage.StorageException: The remote server returned an error:
 (409) Conflict. ---> System.Net.WebException: The remote server returned an err
or: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTC
ommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTC
ommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at azurecopy.AzureBlobCopyHandler.StartCopy(BasicBlobContainer origBlob, Stri
ng DestinationUrl, DestinationBlobType destBlobType)
   at azurecopycommand.Program.DoNormalCopy()
   at azurecopycommand.Program.Main(String[] args)
Request Information
RequestID:c8281c80-0001-012a-3a3a-f967c4000000
RequestDate:Thu, 18 Aug 2016 10:24:29 GMT
StatusMessage:There is currently a pending copy operation.
ErrorCode:PendingCopyOperation

**Comment by kpfaulkner** [comment]
Hi

Currently there is no aborting a copy when using the BlobCopy flag (the point being that the control has been passed off to Azure to handle). This feature is on the backlog of operations to add, but is currently not there.

Can you confirm how you got that stacktrace? Was it a case of the copying operation was progressing fine and this was only generated once you tried killing it? (ctrl+c ?)

Thanks

Ken

**Comment by vivekanandia** [comment]
I tried to copy a large amount of data and i found it was taking too much time .so i tried to kill it using (ctrl+C).i thought the copy was aborted.so again tried to copy a small piece of data into my blob.That is when i got this stacktrace.

Also i want to check with you if i can copy a single file of 5 GB from s3 to blob through your utility. 

Thanks 
Vivek

**Comment by kpfaulkner** [comment]
Hi

I've only not tried a single file of that size, but I can't think of a
reason why it wouldn't work.

The copy currently wont be aborted when you ctrl+c (I'm adding that feature
soon) due to Azure itself controlling the copy and not the application.

Ken
