### ISSUE TITLE
creation of a folder "no name"

### ISSUE THREAD

**Issue by vivekanandia** [kpfaulkner/azurecopy#13]
when i copy a  folder from s3  to azure blob it creates a folder no-name how to overcome this?

**Comment by kpfaulkner** [comment]
Can you explain a little further please?
Is it literally a container which appears to have no characters in its name? Or is it a container literally called "no-name" ?

Thanks

Ken

**Comment by vivekanandia** [comment]
It is a container literally called "no-name"

**Comment by kpfaulkner** [comment]
Hmmm I dont have any code that creates a container that name.
I'll investigate when I can, but that sounds very odd.

**Comment by kpfaulkner** [comment]
Do you have a way a reproducing this?
