### ISSUE TITLE
AWS S3 bucket: Unknown error generated (version 1.1.7.0)

### ISSUE THREAD

**Issue by pazdev** [kpfaulkner/azurecopy#8]
When i am trying to access the list of items in the S3 shows the below error:
azurecopy (version 1.1.7.0)

> azurecopy.exe -list "https://*******_.s3.amazonaws.com" -db
> GetHandler start
> GetHandler retrieved azurecopy.S3Handler
> container name ***_****
> Unknown error generated. Please report to Github page https://github.com/kpfaulkner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag.
>    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
>    at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
>    at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
>    at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.S3.Internal.AmazonS3KmsHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
>    at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
>    at Amazon.S3.AmazonS3Client.GetBucketLocation(GetBucketLocationRequest request)
>    at Amazon.S3.AmazonS3Client.GetBucketLocation(String bucketName)
>    at azurecopy.Utils.S3Helper.GenerateS3Client(String accessKey, String secretKey, String bucketName)
>    at azurecopy.S3Handler.ListBlobsInContainer(String containerName, String blobPrefix, Boolean debug)
>    at azurecopycommand.Program.DoList(Boolean debugMode)
>    at azurecopycommand.Program.Process(Boolean debugMode)
>    at azurecopycommand.Program.Main(String[] args)

**Comment by adnanjt** [comment]
I have a similar error. Did someone figured it out ?
